Introduces MockLLM and provides an example
log10-io/log10 pull request #130
Opened 2024-04-01 21:55 UTC by delip

**Rationale:** For testing and other purposes, we need a Log10 LLM instance that mimics an LLM chat call but doesn't rely on existing LLMs, local or otherwise. The NoopLLM class provides an interface that always produces a constant output. However, for testing feedback/logging, you might want to have a mock LLM that produces different but deterministic outputs for different inputs. This PR provides that.

As a choice, the current implementation only provides `.chat()` to facilitate my current work and leaves `.text()` for future implementation.

2024-04-09 18:05 UTC, wenzhe-log10 requested changes
Thanks for contributing. 

High level question - what's the use case for the MockLLM? do we expect the user to set prompt messages and response message directly?

Please also run `ruff check log10 examples` and `ruff format log10 examples` for lint/format. current check failed.

2024-04-10 03:33 UTC, delip commented on log10/llm.py
> +        content = self.mock_function(messages[-1].content)
@wenzhe-log10 yes, extra check won't hurt. will do. 

Yes, mock_function does that. However, I will update this with another commit that does what you are asking for from a different interface.

2024-04-10 03:35 UTC, delip commented on log10/llm.py
> +    See examples/feedback/echo for an example.
Sure. I like yours. I will add that.

2024-04-10 21:14 UTC, delip commented on log10/llm.py
> +                        "content": content,
please check the `chat_expected` method I will be committing soon.

2024-04-12 17:47 UTC, wenzhe-log10 requested changes
cool. looks good. 
Do we still need the two example files in `examples/feedback/echo`? Maybe remove since you have add the doc string now.
Last thing is to update the ruff format (failed [here](https://github.com/log10-io/log10/actions/runs/8665651511/job/23764791278?pr=130)).

2024-06-21 20:49 UTC, wenzhe-log10 commented
stale PR. closing this for now

2024-06-21 20:49 UTC, closed without merging